// Updated avatars list
export const AVATARS = [
  require('../../assets/avatars/avatar_0.png'),
  require('../../assets/avatars/avatar_1.png'),
  require('../../assets/avatars/avatar_2.png'),
  require('../../assets/avatars/avatar_3.png'),
  require('../../assets/avatars/avatar_4.png'),
  require('../../assets/avatars/avatar_5.png'),
  require('../../assets/avatars/avatar_6.png'),
  require('../../assets/avatars/avatar_7.png'),
  require('../../assets/avatars/avatar_8.png'),
  require('../../assets/avatars/avatar_9.png'),
  require('../../assets/avatars/avatar_10.png'),
  require('../../assets/avatars/avatar_11.png'),
  require('../../assets/avatars/avatar_12.png'),
  require('../../assets/avatars/avatar_13.png'),
  require('../../assets/avatars/avatar_14.png'),
  require('../../assets/avatars/avatar_15.png'),
  require('../../assets/avatars/avatar_16.png'),
  require('../../assets/avatars/avatar_17.png'),
  require('../../assets/avatars/avatar_18.png'),
  require('../../assets/avatars/avatar_19.png'),
];
